version: "3.8"

services:
  user-service:
    image: openjdk:21-jdk
    build: ./microservices/user-service
    ports:
      - "8081:8081"
    environment:
      MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
      MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
      MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
      MYSQL_ADDON_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      MYSQL_ADDON_PORT: ${MYSQL_ADDON_PORT}

  notification-service:
    image: openjdk:21-jdk
    build: ./microservices/notification-service
    ports:
      - "8082:8082"
    environment:
      MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
      MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
      MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
      MYSQL_ADDON_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      MYSQL_ADDON_PORT: ${MYSQL_ADDON_PORT}

  chat-service:
    image: openjdk:21-jdk
    build: ./microservices/chat-service
    ports:
      - "8083:8083"
    environment:
      MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
      MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
      MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
      MYSQL_ADDON_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      MYSQL_ADDON_PORT: ${MYSQL_ADDON_PORT}

  product-service:
    image: openjdk:21-jdk
    build: ./microservices/product-service
    ports:
      - "8084:8084"
    environment:
      MYSQL_ADDON_HOST: ${MYSQL_ADDON_HOST}
      MYSQL_ADDON_DB: ${MYSQL_ADDON_DB}
      MYSQL_ADDON_USER: ${MYSQL_ADDON_USER}
      MYSQL_ADDON_PASSWORD: ${MYSQL_ADDON_PASSWORD}
      MYSQL_ADDON_PORT: ${MYSQL_ADDON_PORT}

  api-gateway:
    image: openjdk:21-jdk
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - notification-service
      - chat-service
      - product-service

  front-react:
    build: ./front-react
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
